### ISSUE TITLE
npm install 出错，帮忙看看，谢谢了

### ISSUE THREAD

**Issue by derekzhan** [bigsui/shopping-react-native#16]
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:827:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm WARN addRemoteGit  git://github.com/facebook/react.git#b4e74e38e43ac53af8acd62c78c9213be0194245 resetting remote C:\Users\Administrator\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-b4e74e38e43ac53af8acd62c78c9213be0194245-1590fb28 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }

**Comment by ZrbJava** [comment]
+1

**Comment by bigsui** [comment]
当时写的 react版本太老了，回头更新重写下
